### PR TITLE
MSYS2 package count

### PR DESCRIPTION
**Pull request by darealshinji**

### CODE REVIEW

**Comment by woodruffw** [comment]
Since MSYS uses `pacman`, it's probably better to do the Windows equivalent of `glob(3)` on wherever MSYS keeps the `pacman` local cache (`/var/lib/pacman/local/` on *nix). That should be faster than the fork/exec cycle needed by `popen`.

**Comment by woodruffw** [comment]
Looks like [`FindFirstFile`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364418(v=vs.85).aspx) is the standard way to do this with Win32.

**Comment by darealshinji** [comment]
`glob(3)` may still be supported by Msys2 and Cygwin.

**Comment by woodruffw** [comment]
In that case, go with that.

**Comment by darealshinji** [comment]
Did a test and both Cygwin and MSYS2 provide `glob(3)`. I'll use that then.

**Comment by darealshinji** [comment]
I've rewritten the package detection.

**Comment by woodruffw** [comment]
Merged, thanks!

**Pull request merged**
